
-- 1. ADDING PARTITION TO ARCHIVAL TABLE - CLP_HISTORY.CALL_LOG_MAST_HIST
alter table CLP_HISTORY.CALL_LOG_MAST_HIST ADD partition SYS_P40933 VALUES LESS THAN (to_date(20220301, 'YYYYMMDD'));

-- 2. EXCHANGE PARTITION FROM CLP_TRANSACTIONAL.CALL_LOG_MAST TABLE TO CLP_TRANSACTIONAL.CALL_LOG_MAST_STG
alter table CLP_TRANSACTIONAL.CALL_LOG_MAST  EXCHANGE PARTITION SYS_P40933 WITH TABLE CLP_TRANSACTIONAL.CALL_LOG_MAST_STG WITHOUT VALIDATION update global indexes;

-- 3. EXCHANGE PARTITION FROM CLP_TRANSACTIONAL.CALL_LOG_MAST_STG TABLE TO CLP_HISTORY.CALL_LOG_MAST_HIST
alter table CLP_HISTORY.CALL_LOG_MAST_HIST  EXCHANGE PARTITION SYS_P40933 WITH TABLE CLP_TRANSACTIONAL.CALL_LOG_MAST_STG WITHOUT VALIDATION update global indexes;
	
-- 4. NUMBER OF ROWS MOVED FROM CLP_TRANSACTIONAL.CALL_LOG_MAST TO CLP_HISTORY.CALL_LOG_MAST_HIST
select  NVL(NUM_ROWS,0) from all_tab_partitions WHERE PARTITION_NAME = 'SYS_P40933' AND TABLE_NAME='CALL_LOG_MAST_HIST';

-- 5. DROPPING MAIN TABLE PARTITION CLP_TRANSACTIONAL.CALL_LOG_MAST
alter table CLP_TRANSACTIONAL.CALL_LOG_MAST drop partition SYS_P40933 update global indexes

